version: '3.7'
services:
  vpn-server:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard-client
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi #set correct timezone
      - SERVERURL=auto #Wireguard VPN server address      
    volumes:
      - ./client/config:/config
      - /usr/src:/usr/src # location of kernel headers
      - /lib/modules:/lib/modules
#    ports:
#      - 51820:51820/udp
    network_mode: "host"  
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
